version: '3.9'
services:
    postgres:
        image: postgres:13.3
        environment:
            POSTGRES_DB: 'auth'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
            PGDATA: '/var/lib/postgresql/data/auth'
        volumes:
            - ../2. Init Database:/docker-entrypoint-initdb.d
            - .:/var/lib/postgresql/data
        ports:
            - '5433:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres -d auth']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 4G
